version:              '3.3'

services:
  calico:
    image:            calico/node:v3.1.3
    networks:
       - host
    # ports:
    #  - 8025:8025
    environment:
      - ETCD_ENDPOINTS=http://127.0.0.1:2379
    volumes:
      - calico:/var/lib/calico
      - calicologs:/var/log/calico
      - /run/docker/plugins:/run/docker/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode:           global
      resources:
        limits:
          cpus:       '0.50'
          memory:     200M
        reservations:
          cpus:       '0.20'
          memory:     50M
  etcd:
    image:            bitnami/etcd:3.3.9
    networks:
       - host
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://10.16.74.137:2379
    volumes:
      - etcd_data:/bitnami
    deploy:
      mode:           global
      resources:
        limits:
          cpus:       '0.50'
          memory:     200M
        reservations:
          cpus:       '0.20'
          memory:     50M
volumes:
  etcd_data:
    driver:           local
  calico:
    driver:           local
  calicologs:
    driver:           local

networks:
  host:
    external:         true
