version:                '3.3'

services:
   liveevents:
     image:             giorgiocasciaro/ubuntu-node:v3
     # logging:
     #   driver:        none
     working_dir:       /microservice
     command:           sh -c "npm run watch_start"
     environment:
       uploadPath:      /uploads/
       schemaHost:      'http://schema:10000'
       serviceName:     liveevents
      #  netHost:         liveevents
      #  netHostHttpPublicPort: 10080
       netCors:         http://localhost:82,http://127.0.0.1:82,http://localhost:8080,http://127.0.0.1:8080,http://localhost:10080,http://127.0.0.1:10080
       NODE_ENV:        development
       sendEmails:      'true'
       smtpConfigJson: '{ "host": "fakesmtp", "port": 1025, "secure": false }'
     volumes:
       - ../../liveevents:/microservice
       - ../../../../civil_microservices_shared_modules/:/microservice/node_modules
       - ../../../NPM/jesus:/microservice/node_modules/sint-bit-jesus
       - ../../../NPM/cqrs:/microservice/node_modules/sint-bit-cqrs
       - ../../../NPM/sint-bit-utils:/microservice/node_modules/sint-bit-utils
       - ../../../FS/:/uploads/
     ports:
       - 11000:10080
     networks:
       - microservicesNet

networks:
  microservicesNet:
    driver:             bridge
