version:                '3.3'

services:
   liveevents:
     image:             giorgiocasciaro/civil-microservices-liveevents:0
     command:           sh -c "npm run start "
     environment:
       uploadPath:      /uploads/
       schemaHost:      'http://schema:10000'
       confirmEmailUrl: http://localhost:8080/#/registration/ConfirmEmail/
       serviceName:     liveevents
       netHost:         liveevents
      #  netHostHttpPublicPort: 10080
      #  netCors:         http://localhost:82,http://127.0.0.1:82,http://localhost:8080,http://127.0.0.1:8080,http://localhost:10080,http://127.0.0.1:10080
      #  elasticsearchHost: elasticsearch:9200
       aerospikeHosts:  aerospike:3000
       NODE_ENV:        test
       sendEmails:      'true'
       smtpConfigJson: '{ "host": "fakesmtp", "port": 1025, "secure": false }'
     deploy:
       endpoint_mode: dnsrr
       # placement:
       #   constraints: [node.role == manager]
      #  mode:      global
       replicas:    1
     networks:
       - microservicesNet
       - aerospike

networks:
  microservicesNet:
    driver:             overlay
  aerospike:
    driver:             overlay
