apiVersion: v1
kind: Service
metadata:
  name: civil-microservices-www
  namespace: civil-connect
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  - port: 443
    name: https
    targetPort: 443
    nodePort: 30443
    protocol: TCP
  - port: 81
    name: test1
    targetPort: 81
    nodePort: 30081
    protocol: TCP
  - port: 82
    name: test2
    targetPort: 82
    nodePort: 30082
    protocol: TCP
  type: NodePort
  selector:
    run: fcivil-microservices-www
